[workspace]
resolver = "2"
members = ["crates/protocol", "crates/download-core", "crates/platform", "crates/native-host"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Leon Erwin Huber"]

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = true
