// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Browser candidate returned from platform detection.
 */
export type BrowserDto = { 
/**
 * Browser name.
 */
name: string, 
/**
 * Whether the native host is registered.
 */
registered: boolean, };
