// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result returned after accepting a download request.
 */
export type CreateDownloadResponse = { 
/**
 * Assigned download identifier.
 */
id: string, 
/**
 * Resolved destination path.
 */
destination: string, };
