// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new download.
 */
export type CreateDownloadRequest = { 
/**
 * The URL to download.
 */
url: string, 
/**
 * Target directory path.
 */
destinationPath: string, };
