// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A download summary sent to the frontend.
 */
export type DownloadDto = { 
/**
 * Download identifier (UUIDv7 as string).
 */
id: string, 
/**
 * Original request URL.
 */
url: string, 
/**
 * Resolved destination path.
 */
destination: string, 
/**
 * Current status in snake_case.
 */
status: string, 
/**
 * Bytes written so far.
 */
downloaded: bigint, 
/**
 * Total bytes when known.
 */
total: bigint | null, 
/**
 * Stable error code when failed.
 */
errorCode: string | null, 
/**
 * Restart notice for resumed transfers.
 */
restartNotice: string | null, 
/**
 * ISO 8601 creation timestamp.
 */
createdAt: string, };
