// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress event emitted during a transfer.
 */
export type ProgressDto = { 
/**
 * Download identifier.
 */
id: string, 
/**
 * Bytes written so far.
 */
downloaded: bigint, 
/**
 * Total bytes when known.
 */
total: bigint | null, };
