// Auto-generated by ts-rs. DO NOT EDIT.
// Generated from: crates/download-core/src/models/dto.rs

type DownloadDto = { 
/**
 * Download identifier (UUIDv7 as string).
 */
id: string, 
/**
 * Original request URL.
 */
url: string, 
/**
 * Resolved destination path.
 */
destination: string, 
/**
 * Current status in snake_case.
 */
status: string, 
/**
 * Bytes written so far.
 */
downloaded: bigint, 
/**
 * Total bytes when known.
 */
total: bigint | null, 
/**
 * Stable error code when failed.
 */
errorCode: string | null, 
/**
 * Restart notice for resumed transfers.
 */
restartNotice: string | null, 
/**
 * ISO 8601 creation timestamp.
 */
createdAt: string, };
type ProgressDto = { 
/**
 * Download identifier.
 */
id: string, 
/**
 * Bytes written so far.
 */
downloaded: bigint, 
/**
 * Total bytes when known.
 */
total: bigint | null, };
type CreateDownloadRequest = { 
/**
 * The URL to download.
 */
url: string, 
/**
 * Target directory path.
 */
destinationPath: string, };
type CreateDownloadResponse = { 
/**
 * Assigned download identifier.
 */
id: string, 
/**
 * Resolved destination path.
 */
destination: string, };
type BrowserDto = { 
/**
 * Browser name.
 */
name: string, 
/**
 * Whether the native host is registered.
 */
registered: boolean, };
