//! Integration test that exports TypeScript bindings from DTO types.
//!
//! Run with: `cargo test -p freeloader-download-core --features ts`

#[cfg(feature = "ts")]
#[test]
fn export_typescript_bindings() {
    use freeloader_download_core::models::dto::{
        BrowserDto, CreateDownloadRequest, CreateDownloadResponse, DownloadDto, ProgressDto,
    };
    use ts_rs::TS;

    let out_dir =
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../apps/desktop/src");

    std::fs::create_dir_all(&out_dir).expect("create frontend src dir");

    let mut output = String::new();
    output.push_str("// Auto-generated by ts-rs. DO NOT EDIT.\n");
    output.push_str("// Generated from: crates/download-core/src/models/dto.rs\n\n");

    let types: &[(&str, String)] = &[
        ("DownloadDto", DownloadDto::decl()),
        ("ProgressDto", ProgressDto::decl()),
        ("CreateDownloadRequest", CreateDownloadRequest::decl()),
        ("CreateDownloadResponse", CreateDownloadResponse::decl()),
        ("BrowserDto", BrowserDto::decl()),
    ];

    for (_name, decl) in types {
        output.push_str(&decl);
        output.push('\n');
    }

    std::fs::write(out_dir.join("generated-types.ts"), &output).expect("write generated-types.ts");

    eprintln!("Wrote {len} types to generated-types.ts", len = types.len());
}

#[cfg(not(feature = "ts"))]
#[test]
fn export_is_disabled_without_ts_feature() {
    // This test exists so `cargo test` (without --features ts) still passes.
}
